stages:
  - build
  - up

before_script:
  - echo $CI_JOB_TOKEN | docker login -u gitlab-ci-token --password-stdin registry.gitlab.com

after_script:
  - docker logout registry.gitlab.com

variables:
  TAG: $CI_COMMIT_REF_NAME

build:
  stage: build
  script:
    - docker compose build
    - docker compose push
  only:
    - dev
    - master
  tags:
    - builder

up_dev:
  environment: development
  stage: up
  script:
    - docker compose pull
    - docker compose up -d --no-build
  only:
    - dev
  tags:
    - development

up_prod:
  environment: production
  stage: up
  script:
    - docker compose pull
    - docker compose up -d --no-build
  only:
    - master
  tags:
    - production

migrate_db_dev:
  stage: up
  script: docker compose exec backend python manage.py migrate
  when: manual
  environment: dev
  rules:
    - if: $CI_COMMIT_BRANCH == "dev"
      changes:
      - backend/core/migrations/*
  tags:
    - development

migrate_db_prod:
  stage: up
  script: docker compose exec backend python manage.py migrate
  when: manual
  environment: production
  rules:
    - if: $CI_COMMIT_BRANCH == "master"
      changes:
        - backend/core/migrations/*
  tags:
    - production
