version: '3'

services:
  frontend:
    build: .
    image: registry.gitlab.com/labab-dev/promvisio/frontend:${TAG:-latest}
    restart: unless-stopped
    volumes:
      - "${DJANGO_MEDIA_VOLUME:-./backend/mediafiles}:/var/www/mediafiles:ro"
      - "${DJANGO_STATIC_VOLUME:-./backend/staticfiles}:/var/www/staticfiles:ro"
    ports:
      - "127.0.0.1:8007:80"
    depends_on:
      - backend

  backend:
    build: ./backend
    image: registry.gitlab.com/labab-dev/promvisio/backend:${TAG:-latest}
    restart: unless-stopped
    environment:
      DJANGO_SECRET_KEY: $DJANGO_SECRET_KEY
      DJANGO_DB_URL: $DJANGO_DB_URL
      DJANGO_ALLOWED_HOSTS: $DJANGO_ALLOWED_HOSTS
      DJANGO_CORS_ALLOWED_ORIGINS: $DJANGO_CORS_ALLOWED_ORIGINS
      DJANGO_WORKERS_COUNT: $DJANGO_WORKERS_COUNT
      DJANGO_ENABLE_SWAGGER: $DJANGO_ENABLE_SWAGGER
      DJANGO_ENABLE_SENTRY: $DJANGO_ENABLE_SENTRY
      DJANGO_SENTRY_DSN: $DJANGO_SENTRY_DSN
      DJANGO_ENABLE_EMAILS: $DJANGO_ENABLE_EMAILS
      DJANGO_EMAIL_HOST: $DJANGO_EMAIL_HOST
      DJANGO_EMAIL_PORT: $DJANGO_EMAIL_PORT
      DJANGO_EMAIL_HOST_USER: $DJANGO_EMAIL_HOST_USER
      DJANGO_EMAIL_HOST_PASSWORD: $DJANGO_EMAIL_HOST_PASSWORD
    command: gunicorn config.wsgi:application -w ${DJANGO_WORKERS_COUNT:-1}
    volumes:
      - "${DJANGO_MEDIA_VOLUME:-./backend/mediafiles}:/app/mediafiles"
      - "${DJANGO_STATIC_VOLUME:-./backend/staticfiles}:/app/staticfiles"
    depends_on:
      - postgres

  postgres:
    image: postgres:13
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_DB: $POSTGRES_DB
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data: {}
