version: '3'

services:
  frontend:
    build: .
    image: registry.gitlab.com/labab-dev/promvisio/frontend:${TAG:-latest}
    restart: unless-stopped
    ports:
      - "127.0.0.1:8004:80"
    volumes:
      - "${DJANGO_MEDIA_VOLUME:-./backend/mediafiles}:/var/www/mediafiles:ro"
      - "${DJANGO_STATIC_VOLUME:-./backend/staticfiles}:/var/www/staticfiles:ro"
    depends_on:
      - admin

  admin:
    build: ./backend
    image: registry.gitlab.com/labab-dev/promvisio/admin:${TAG:-latest}
    restart: unless-stopped
    environment:
      DJANGO_SECRET_KEY: $DJANGO_SECRET_KEY
      DJANGO_DB_URL: $DJANGO_DB_URL
      DJANGO_ALLOWED_HOSTS: $DJANGO_ALLOWED_HOSTS
      DJANGO_CORS_ALLOWED_ORIGINS: $DJANGO_CORS_ALLOWED_ORIGINS
      DJANGO_WORKERS_COUNT: $DJANGO_WORKERS_COUNT
      DJANGO_ENABLE_SWAGGER: $DJANGO_ENABLE_SWAGGER
      DJANGO_ENABLE_SENTRY: $DJANGO_ENABLE_SENTRY
      DJANGO_SENTRY_DSN: $DJANGO_SENTRY_DSN
    volumes:
      - "${DJANGO_MEDIA_VOLUME:-./backend/mediafiles}:/app/mediafiles"
      - "${DJANGO_STATIC_VOLUME:-./backend/staticfiles}:/app/staticfiles"
    depends_on:
      - db

  db:
    image: postgres:13
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_DB: $POSTGRES_DB
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data: {}
