exclude: 'config/settings|migrations'

repos:
  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        args:
          - "--ignore=E501,W503"
  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black
