# Generated by Django 4.2.2 on 2023-06-06 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("wagtailimages", "0025_alter_image_file_alter_rendition_file"),
        ("core", "0006_potentialpage_potentialpagevideo_potentialpageimage"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="potentialpageimage",
            options={
                "ordering": ["sort_order"],
                "verbose_name": "Фото",
                "verbose_name_plural": "Фото",
            },
        ),
        migrations.AlterModelOptions(
            name="potentialpagevideo",
            options={
                "ordering": ["sort_order"],
                "verbose_name": "Видео",
                "verbose_name_plural": "Видео",
            },
        ),
        migrations.AlterField(
            model_name="potentialpageimage",
            name="image",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="wagtailimages.image",
                verbose_name="Фотография",
            ),
        ),
        migrations.AlterField(
            model_name="potentialpagevideo",
            name="iframe",
            field=models.CharField(
                blank=True,
                editable=False,
                max_length=255,
                null=True,
                verbose_name="Iframe",
            ),
        ),
    ]
