# Generated by Django 4.2.2 on 2023-06-06 23:17

import core.models.misc
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_remove_gallerypage_content_galleryvideo_galleryimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="galleryvideo",
            name="url_or_iframe",
            field=models.CharField(
                help_text="Тут должен быть iframe или ссылка на youtube/rutube",
                max_length=255,
                validators=[core.models.misc.validate_video],
                verbose_name="Код для встраивания",
            ),
        ),
        migrations.AlterField(
            model_name="potentialpagevideo",
            name="iframe",
            field=models.CharField(
                blank=True,
                default="",
                editable=False,
                max_length=255,
                verbose_name="Iframe",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="potentialpagevideo",
            name="url_or_iframe",
            field=models.CharField(
                help_text="Тут должен быть iframe или ссылка на youtube/rutube",
                max_length=255,
                validators=[core.models.misc.validate_video],
                verbose_name="Код для встраивания",
            ),
        ),
    ]
