# Generated by Django 4.2.2 on 2023-06-07 09:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_alter_galleryvideo_url_or_iframe_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="gallerypage",
            name="pagination_page_size",
            field=models.IntegerField(
                default=6,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="Размер страницы пагинации галереи",
            ),
        ),
        migrations.AddField(
            model_name="potentialpage",
            name="pagination_page_size",
            field=models.IntegerField(
                default=6,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="Размер страницы пагинации галереи",
            ),
        ),
    ]
