# Generated by Django 4.2.2 on 2023-06-07 20:27

import core.blocks.technical
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import wagtail.fields
import wagtail_headless_preview.models


class Migration(migrations.Migration):
    dependencies = [
        ("wagtailcore", "0083_workflowcontenttype"),
        ("core", "0010_gallerypage_pagination_page_size_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ArticlePage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "datetime",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Дата и время"
                    ),
                ),
                (
                    "source_link",
                    models.URLField(
                        blank=True, null=True, verbose_name="Ссылка внешний источник"
                    ),
                ),
                (
                    "source_link_name",
                    models.CharField(
                        blank=True,
                        null=True,
                        verbose_name="Название ссылки на внешний источник",
                    ),
                ),
                (
                    "source_link_in_new_tab",
                    models.BooleanField(
                        blank=True, verbose_name="Открывать в новой вкладке"
                    ),
                ),
                ("body", wagtail.fields.RichTextField(verbose_name="Контент")),
                (
                    "right_side",
                    wagtail.fields.StreamField(
                        [
                            (
                                "photo",
                                core.blocks.technical.APIImageChooserBlock(
                                    label="Фото"
                                ),
                            )
                        ],
                        use_json_field=True,
                        verbose_name="Контент справа",
                    ),
                ),
            ],
            options={
                "verbose_name": "Статья",
                "verbose_name_plural": "Статьи",
                "ordering": ["-datetime"],
            },
            bases=(wagtail_headless_preview.models.HeadlessMixin, "wagtailcore.page"),
        ),
    ]
