# Generated by Django 4.2.2 on 2023-06-07 21:02

import core.blocks.technical
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import wagtail.fields
import wagtail_headless_preview.models


class Migration(migrations.Migration):
    dependencies = [
        ("wagtailcore", "0083_workflowcontenttype"),
        ("core", "0011_articlepage"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewsPage",
            fields=[
                (
                    "page_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="wagtailcore.page",
                    ),
                ),
                (
                    "articles_count",
                    models.PositiveIntegerField(
                        default=6,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Количество статей на странице",
                    ),
                ),
            ],
            options={
                "verbose_name": "Вестник",
                "verbose_name_plural": "Вестник",
            },
            bases=(wagtail_headless_preview.models.HeadlessMixin, "wagtailcore.page"),
        ),
        migrations.AlterField(
            model_name="articlepage",
            name="right_side",
            field=wagtail.fields.StreamField(
                [("image", core.blocks.technical.APIImageChooserBlock(label="Фото"))],
                use_json_field=True,
                verbose_name="Контент справа",
            ),
        ),
    ]
