# Generated by Django 4.2.2 on 2023-06-07 21:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0012_newspage_alter_articlepage_right_side"),
    ]

    operations = [
        migrations.AddField(
            model_name="newspage",
            name="heading",
            field=models.CharField(default="Вестник", verbose_name="Большой текст"),
        ),
    ]
