# Generated by Django 4.2.2 on 2023-06-09 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("wagtailimages", "0025_alter_image_file_alter_rendition_file"),
        ("core", "0013_newspage_heading"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedback",
            name="message",
            field=models.TextField(blank=True, verbose_name="Сообщение"),
        ),
        migrations.AlterField(
            model_name="potentialpagevideo",
            name="thumbnail",
            field=models.ForeignKey(
                blank=True,
                help_text="Оставьте это поле пустым для автоматической загрузки превью",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="wagtailimages.image",
                verbose_name="Превью видео",
            ),
        ),
    ]
